version: "3.8"
services:
  php-fpm:
    build:
      context: .
      args:
        NEWRELIC_LICENSE_KEY: ${NEWRELIC_LICENSE_KEY}
    working_dir: /usr/local/app/hello-newrelic
    volumes:
      - .:/usr/local/app/hello-newrelic

  nginx:
    build: docker/nginx
    ports:
      - ${HTTP_PORT:-8080}:80
    volumes:
      - .:/usr/local/app/hello-newrelic
